<a href="https://colab.research.google.com/github/Dell0071/hockey/blob/main/Hockey_Betting_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge

In [2]:
path = "https://github.com/Dell0071/hockey/raw/main/hockey.csv"
hockey = pd.read_csv(path)
hockey

        Date               visitor  ...                 home home_goals
0    1/13/21       St. Louis Blues  ...   Colorado Avalanche          1
1    1/13/21     Vancouver Canucks  ...      Edmonton Oilers          3
2    1/13/21   Pittsburgh Penguins  ...  Philadelphia Flyers          6
3    1/13/21    Chicago Blackhawks  ...  Tampa Bay Lightning          5
4    1/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          5
..       ...                   ...  ...                  ...        ...
205  2/13/21         Boston Bruins  ...   New York Islanders          4
206  2/13/21  Vegas Golden Knights  ...      San Jose Sharks          1
207  2/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          1
208  2/13/21        Calgary Flames  ...    Vancouver Canucks          3
209  2/13/21       Ottawa Senators  ...        Winnipeg Jets          1

[210 rows x 5 columns]

In [3]:
hockey.drop(columns=hockey.columns[5:9])

        Date               visitor  ...                 home home_goals
0    1/13/21       St. Louis Blues  ...   Colorado Avalanche          1
1    1/13/21     Vancouver Canucks  ...      Edmonton Oilers          3
2    1/13/21   Pittsburgh Penguins  ...  Philadelphia Flyers          6
3    1/13/21    Chicago Blackhawks  ...  Tampa Bay Lightning          5
4    1/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          5
..       ...                   ...  ...                  ...        ...
205  2/13/21         Boston Bruins  ...   New York Islanders          4
206  2/13/21  Vegas Golden Knights  ...      San Jose Sharks          1
207  2/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          1
208  2/13/21        Calgary Flames  ...    Vancouver Canucks          3
209  2/13/21       Ottawa Senators  ...        Winnipeg Jets          1

[210 rows x 5 columns]

In [4]:
hockey['goal_difference'] = hockey['home_goals'] - hockey['visitor_goals']

In [5]:
hockey.drop(columns=hockey.columns[5:9])

        Date               visitor  ...                 home home_goals
0    1/13/21       St. Louis Blues  ...   Colorado Avalanche          1
1    1/13/21     Vancouver Canucks  ...      Edmonton Oilers          3
2    1/13/21   Pittsburgh Penguins  ...  Philadelphia Flyers          6
3    1/13/21    Chicago Blackhawks  ...  Tampa Bay Lightning          5
4    1/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          5
..       ...                   ...  ...                  ...        ...
205  2/13/21         Boston Bruins  ...   New York Islanders          4
206  2/13/21  Vegas Golden Knights  ...      San Jose Sharks          1
207  2/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          1
208  2/13/21        Calgary Flames  ...    Vancouver Canucks          3
209  2/13/21       Ottawa Senators  ...        Winnipeg Jets          1

[210 rows x 5 columns]

In [6]:
hockey['home_win'] = np.where(hockey['goal_difference'] > 0, 1, 0)
hockey['home_loss'] = np.where(hockey['goal_difference'] < 0, 1, 0)

In [7]:
hockey.drop(columns=hockey.columns[5:9])

        Date               visitor  ...                 home home_goals
0    1/13/21       St. Louis Blues  ...   Colorado Avalanche          1
1    1/13/21     Vancouver Canucks  ...      Edmonton Oilers          3
2    1/13/21   Pittsburgh Penguins  ...  Philadelphia Flyers          6
3    1/13/21    Chicago Blackhawks  ...  Tampa Bay Lightning          5
4    1/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          5
..       ...                   ...  ...                  ...        ...
205  2/13/21         Boston Bruins  ...   New York Islanders          4
206  2/13/21  Vegas Golden Knights  ...      San Jose Sharks          1
207  2/13/21    Montreal Canadiens  ...  Toronto Maple Leafs          1
208  2/13/21        Calgary Flames  ...    Vancouver Canucks          3
209  2/13/21       Ottawa Senators  ...        Winnipeg Jets          1

[210 rows x 5 columns]

In [8]:

hockey_visitor = pd.get_dummies(hockey['visitor'], dtype=np.int64)
hockey_home = pd.get_dummies(hockey['home'], dtype=np.int64)

In [9]:
hockey_visitor

     Anaheim Ducks  Arizona Coyotes  ...  Washington Capitals  Winnipeg Jets
0                0                0  ...                    0              0
1                0                0  ...                    0              0
2                0                0  ...                    0              0
3                0                0  ...                    0              0
4                0                0  ...                    0              0
..             ...              ...  ...                  ...            ...
205              0                0  ...                    0              0
206              0                0  ...                    0              0
207              0                0  ...                    0              0
208              0                0  ...                    0              0
209              0                0  ...                    0              0

[210 rows x 31 columns]

In [10]:
hockey_model = hockey_home.sub(hockey_visitor) 
hockey_model['goal_difference'] = hockey['goal_difference']

In [11]:
hockey_model

     Anaheim Ducks  Arizona Coyotes  ...  Winnipeg Jets  goal_difference
0                0                0  ...              0               -3
1                0                0  ...              0               -2
2                0                0  ...              0                3
3                0                0  ...              0                4
4                0                0  ...              0                1
..             ...              ...  ...            ...              ...
205              0                0  ...              0                2
206              0                0  ...              0               -2
207              0                0  ...              0               -1
208              0                0  ...              0                2
209              0                0  ...              1               -1

[210 rows x 32 columns]

In [12]:

hockey_model.drop('San Jose Sharks',axis=1)

     Anaheim Ducks  Arizona Coyotes  ...  Winnipeg Jets  goal_difference
0                0                0  ...              0               -3
1                0                0  ...              0               -2
2                0                0  ...              0                3
3                0                0  ...              0                4
4                0                0  ...              0                1
..             ...              ...  ...            ...              ...
205              0                0  ...              0                2
206              0                0  ...              0               -2
207              0                0  ...              0               -1
208              0                0  ...              0                2
209              0                0  ...              1               -1

[210 rows x 31 columns]

In [13]:
hockey_train = hockey_model.drop('San Jose Sharks',axis=1)
lr = Ridge(alpha=0.001) 
X = hockey_train.drop(['goal_difference'],axis=1)
y = hockey_model['goal_difference']

lr.fit(X, y)

Ridge(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [14]:
hockey_ratings = pd.DataFrame(data={'team': X.columns, 'rating': lr.coef_})
hockey_ratings

                     team    rating
0           Anaheim Ducks  0.175459
1         Arizona Coyotes  0.412076
2           Boston Bruins  1.008573
3          Buffalo Sabres -0.376382
4          Calgary Flames  0.388816
5     Carolina Hurricanes  0.936625
6      Chicago Blackhawks -0.149989
7      Colorado Avalanche  1.733022
8   Columbus Blue Jackets -0.349979
9            Dallas Stars  0.283786
10      Detroit Red Wings -0.939583
11        Edmonton Oilers  0.099034
12       Florida Panthers -0.283855
13      Los Angeles Kings  0.426801
14         Minnesota Wild  0.622091
15     Montreal Canadiens  0.752935
16    Nashville Predators -0.903707
17      New Jersey Devils -0.176685
18     New York Islanders  0.038133
19       New York Rangers -0.421427
20        Ottawa Senators -1.672415
21    Philadelphia Flyers  0.452004
22    Pittsburgh Penguins -0.363006
23        St. Louis Blues  0.790308
24    Tampa Bay Lightning  1.406703
25    Toronto Maple Leafs  0.881712
26      Vancouver Canucks -0.498766
27   Vegas Golden Knights  1.125960
28    Washington Capitals -0.161210
29          Winnipeg Jets  0.048683